# Use root/example as user/password credentials

services:

  mongo:
    image: mongo
    restart: always
    env_file: sample.env

  redis:
    image: redis
    restart: always

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80 # nginx
    depends_on:
      - mongo
      - redis
      - backend
    env_file: sample.env

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000 # Expose backend for redirects and frontend access
    depends_on:
      - mongo
      - redis
    env_file: sample.env