# Use root/example as user/password credentials

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis
    restart: always

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80 # nginx
    depends_on:
      - mongo
      - redis
      - backend
    environment:
      BACKEND_URL: http://backend:3000

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URL: mongodb://admin:password@mongo:27017/
      REDIS_URL: redis://redis:6379