# Use root/example as user/password credentials

services:

  mongo:
    image: mongo
    restart: always
    env_file: env_file

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: env_file


  redis:
    image: redis
    restart: always

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80 # nginx
    depends_on:
      - mongo
      - redis
      - backend
    env_file:
      - env_file

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
    env_file:
      - env_file